---
- include: install.yml
  when: install_ppa == False or ansible_pkg_mgr == 'yum'
- include: install-ppa.yml
  when: install_ppa == True and ansible_pkg_mgr == 'apt'
- include: configure.yml
  when: nginx_enabled == true
- include: sites.yml
  when: nginx_enabled == true
